### ISSUE TITLE
Problems with UE5

### ISSUE THREAD

**Issue by JulianGerhard21** [IlgarLunin/UE4GoogleSpeechKit-docs#2]
Good Morning,

yesterday I bought your fantastic work. I followed the documentation with UE 5.0.3 and ended up with the following flow:

I implemented the Microphone check and I am able to hear the recording. As far as I can tell (I am working in this area as a software developer) the quality should be sufficient for STT. If I press R however, sound is captured but the ending node only prints "STT finished" without a real transcription. There is no related log output. 

1. The DefaultEngine.ini in UE5 - the default entries there seem to be different from the ones you described here, especially the bEnabled=true for Voice. Maybe this is a problem?
2. What can I do to get more verbose info of what happens?

To check if my API key works, I tried to use TTS with:

![ue52](https://user-images.githubusercontent.com/42409148/178650933-421cf1bb-71a0-45dd-acdd-444c09fb9961.PNG)

But I ended ab with a totally different async node TTS than the one in your docs. What am I doing wrong here?

Any help would be appreciated! 

Kind regards
Julian

**Comment by IlgarLunin** [comment]
@JulianGerhard21 for the STT node, it looks different because input struct is collapsed (by default), to make it look like on screenshot in the docs - right click on `Params` pin -> split struct

**Comment by IlgarLunin** [comment]
About debug output. I tried to output all the info into `Output Log` panel
![image](https://user-images.githubusercontent.com/8058622/178668891-4b9df1f8-cfbf-4d62-8561-631b7eb798d0.png)
